version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region eu-west-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t tribute .
      - docker tag tribute 933186250239.dkr.ecr.eu-west-1.amazonaws.com/tribute-server
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push 933186250239.dkr.ecr.eu-west-1.amazonaws.com/tribute-server
artifacts:
  files:
    - '**/*'