version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - docker run -d --restart=always -p 9999:9999 ubuntu
  post_build:
    commands:
      - echo Build completed on `date`
